staging2:
  url: "https://staging2.vms.carta.healthcare"
  userName: "creator@carta.healthcare"
  password: "BlackMark$FromGospodin2021"

canary2:
  url: "https://canary2.vms.carta.healthcare"
  userName: "creator@carta.healthcare"
  password: "BlackMark$FromGospodin2021"